# Generated by Django 6.0.5 on 2026-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_credit_balance_user_preferred_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
