# Generated by Django 6.0.5 on 2026-06-18 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
        ("users", "0004_add_learning_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learning_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="knowledge.learninggoal",
            ),
        ),
    ]
