# Generated by Django 6.0.5 on 2026-06-20 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_page_pagelexicalitem_page_items_pagepart_and_more'),
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPageProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page progress',
                'verbose_name_plural': 'page progress',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'page'), name='unique_user_page_progress')],
            },
        ),
    ]
