# Generated by Django 6.0.5 on 2026-06-20 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_section_created_by_sectionitem_created_by'),
        ('knowledge', '0002_seed_goals'),
        ('packs', '0003_pack_goals_packitem_pack_items_packreferencesheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='packs.pack')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['pack', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageLexicalItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('display_label', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_lexical_items', to='knowledge.lexicalitem')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_lexical_items', to='content.page')),
            ],
            options={
                'verbose_name': 'page lexical item',
                'verbose_name_plural': 'page lexical items',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='items',
            field=models.ManyToManyField(related_name='pages', through='content.PageLexicalItem', to='knowledge.lexicalitem'),
        ),
        migrations.CreateModel(
            name='PagePart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_type', models.CharField(choices=[('note', 'Teaching Note'), ('fill_blank', 'Fill in the Blank'), ('conversation', 'Conversation')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='content.page')),
            ],
            options={
                'verbose_name': 'page part',
                'verbose_name_plural': 'page parts',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FillBlankPart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_before', models.CharField(max_length=500)),
                ('text_after', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=100)),
                ('hint', models.CharField(blank=True, default='', max_length=255)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fill_blank_parts', to='knowledge.lexicalitem')),
                ('page_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank', to='content.pagepart')),
            ],
            options={
                'verbose_name': 'fill blank part',
                'verbose_name_plural': 'fill blank parts',
            },
        ),
        migrations.CreateModel(
            name='ConversationPart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(blank=True, default='', max_length=255)),
                ('page_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='content.pagepart')),
            ],
            options={
                'verbose_name': 'conversation part',
                'verbose_name_plural': 'conversation parts',
            },
        ),
        migrations.CreateModel(
            name='TeachingNotePart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_note', to='content.pagepart')),
            ],
            options={
                'verbose_name': 'teaching note part',
                'verbose_name_plural': 'teaching note parts',
            },
        ),
        migrations.CreateModel(
            name='ConversationLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('speaker', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('translation', models.CharField(blank=True, default='', max_length=500)),
                ('is_blank', models.BooleanField(default=False)),
                ('blank_answer', models.CharField(blank=True, default='', max_length=200)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='content.conversationpart')),
            ],
            options={
                'verbose_name': 'conversation line',
                'verbose_name_plural': 'conversation lines',
                'ordering': ['conversation', 'order'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'order'), name='unique_line_order_in_conversation')],
            },
        ),
        migrations.AddConstraint(
            model_name='pagelexicalitem',
            constraint=models.UniqueConstraint(fields=('page', 'item'), name='unique_page_item'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('pack', 'order'), name='unique_page_order_in_pack'),
        ),
        migrations.AddConstraint(
            model_name='pagepart',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='unique_part_order_in_page'),
        ),
    ]
