# Generated by Django 6.0.5 on 2026-06-20 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_page_pagelexicalitem_page_items_pagepart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepart',
            name='part_type',
            field=models.CharField(choices=[('note', 'Teaching Note'), ('fill_blank', 'Fill in the Blank'), ('conversation', 'Conversation'), ('table', 'Table')], max_length=20),
        ),
        migrations.CreateModel(
            name='TablePart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headers', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('page_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='content.pagepart')),
            ],
            options={
                'verbose_name': 'table part',
                'verbose_name_plural': 'table parts',
            },
        ),
    ]
