# Generated by Django 6.0.5 on 2026-06-21 12:54

import apps.content.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_pagepart_part_type_tablepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_code', models.CharField(db_index=True, help_text='Level code, e.g. A1.1, A1.2, A2.1', max_length=10)),
                ('pack_slug', models.SlugField(help_text="Pack slug (created automatically if it doesn't exist)", max_length=100)),
                ('topics_file', models.FileField(help_text='Phase 1 JSON: topic list with lexical items', upload_to=apps.content.models._import_upload_path)),
                ('pages_file', models.FileField(help_text='Phase 2 JSON: teaching content (pages + parts)', upload_to=apps.content.models._import_upload_path)),
                ('exercises_file', models.FileField(blank=True, help_text='Phase 3 JSON: practice exercises (optional — can import later)', upload_to=apps.content.models._import_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('result_log', models.TextField(blank=True, default='', help_text='Import results, warnings, and errors')),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('pages_created', models.PositiveIntegerField(default=0)),
                ('exercises_created', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'content import',
                'verbose_name_plural': 'content imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
