from django.contrib import admin, messages
from django.utils.html import format_html

from .models import (
    ContentImport,
    ConversationLine,
    ConversationPart,
    FillBlankPart,
    ImportStatus,
    Level,
    Page,
    PageLexicalItem,
    PagePart,
    Section,
    SectionItem,
    TeachingNotePart,
)
from .services import run_content_import


class SectionItemInline(admin.TabularInline):
    model = SectionItem
    extra = 0
    ordering = ["order"]


@admin.register(Level)
class LevelAdmin(admin.ModelAdmin):
    list_display = ["code", "name", "order"]
    ordering = ["order"]


@admin.register(Section)
class SectionAdmin(admin.ModelAdmin):
    list_display = ["title", "level", "category", "content_type", "order", "item_count"]
    list_filter = ["level", "category", "content_type"]
    ordering = ["level", "category", "order"]
    search_fields = ["title"]
    inlines = [SectionItemInline]

    @admin.display(description="Items")
    def item_count(self, obj: Section) -> int:
        return obj.items.count()


@admin.register(SectionItem)
class SectionItemAdmin(admin.ModelAdmin):
    list_display = ["section", "order", "cells"]
    list_filter = ["section__level", "section__category"]
    ordering = ["section", "order"]
    raw_id_fields = ["section"]


# --- Page admin ---


class PageLexicalItemInline(admin.TabularInline):
    model = PageLexicalItem
    extra = 0
    ordering = ["order"]
    raw_id_fields = ["item"]


class TeachingNotePartInline(admin.StackedInline):
    model = TeachingNotePart
    extra = 0


class FillBlankPartInline(admin.StackedInline):
    model = FillBlankPart
    extra = 0
    raw_id_fields = ["item"]


class ConversationLineInline(admin.TabularInline):
    model = ConversationLine
    extra = 0
    ordering = ["order"]


class ConversationPartInline(admin.StackedInline):
    model = ConversationPart
    extra = 0


class PagePartInline(admin.TabularInline):
    model = PagePart
    extra = 0
    ordering = ["order"]
    show_change_link = True


@admin.register(Page)
class PageAdmin(admin.ModelAdmin):
    list_display = ["title", "pack", "order", "item_count", "part_count"]
    list_filter = ["pack__level", "pack"]
    ordering = ["pack", "order"]
    search_fields = ["title"]
    raw_id_fields = ["pack"]
    inlines = [PageLexicalItemInline, PagePartInline]

    @admin.display(description="Items")
    def item_count(self, obj: Page) -> int:
        return obj.page_lexical_items.count()

    @admin.display(description="Parts")
    def part_count(self, obj: Page) -> int:
        return obj.parts.count()


@admin.register(PagePart)
class PagePartAdmin(admin.ModelAdmin):
    list_display = ["page", "part_type", "order"]
    list_filter = ["part_type"]
    ordering = ["page", "order"]
    inlines = [TeachingNotePartInline, FillBlankPartInline, ConversationPartInline]


@admin.register(ConversationPart)
class ConversationPartAdmin(admin.ModelAdmin):
    list_display = ["page_part", "context"]
    inlines = [ConversationLineInline]


# --- Content Import admin ---


@admin.register(ContentImport)
class ContentImportAdmin(admin.ModelAdmin):
    list_display = [
        "level_code",
        "pack_slug",
        "status_badge",
        "items_created",
        "pages_created",
        "exercises_created",
        "created_at",
    ]
    list_filter = ["status", "level_code"]
    readonly_fields = [
        "status",
        "items_created",
        "pages_created",
        "exercises_created",
        "result_log_display",
        "created_at",
        "updated_at",
    ]
    fieldsets = (
        (
            "Import Configuration",
            {
                "fields": ("level_code", "pack_slug"),
            },
        ),
        (
            "Upload Files",
            {
                "fields": ("topics_file", "pages_file", "exercises_file"),
                "description": (
                    "Upload the 3 JSON files generated by ChatGPT. "
                    "Exercises file is optional — you can import it later."
                ),
            },
        ),
        (
            "Results",
            {
                "fields": (
                    "status",
                    "items_created",
                    "pages_created",
                    "exercises_created",
                    "result_log_display",
                ),
            },
        ),
        (
            "Timestamps",
            {
                "fields": ("created_at", "updated_at"),
                "classes": ("collapse",),
            },
        ),
    )
    actions = ["run_import", "clean_and_reimport"]

    @admin.display(description="Status")
    def status_badge(self, obj: ContentImport) -> str:
        colors = {
            ImportStatus.PENDING: "#6c757d",
            ImportStatus.PROCESSING: "#0d6efd",
            ImportStatus.COMPLETED: "#198754",
            ImportStatus.FAILED: "#dc3545",
        }
        color = colors.get(obj.status, "#6c757d")
        return format_html(
            '<span style="color: {}; font-weight: bold;">{}</span>',
            color,
            obj.get_status_display(),
        )

    @admin.display(description="Import Log")
    def result_log_display(self, obj: ContentImport) -> str:
        if not obj.result_log:
            return "No log yet — run the import first."
        return format_html("<pre style='white-space: pre-wrap;'>{}</pre>", obj.result_log)

    @admin.action(description="Run import (create content from uploaded files)")
    def run_import(self, request, queryset):
        for ci in queryset:
            if ci.status == ImportStatus.COMPLETED:
                self.message_user(
                    request,
                    f"'{ci}' already completed. Use 'Clean & re-import' to redo.",
                    messages.WARNING,
                )
                continue
            try:
                run_content_import(ci, clean=False)
                self.message_user(
                    request,
                    f"'{ci}' imported: {ci.items_created} items, "
                    f"{ci.pages_created} pages, {ci.exercises_created} exercises.",
                    messages.SUCCESS,
                )
            except Exception as exc:
                self.message_user(request, f"'{ci}' failed: {exc}", messages.ERROR)

    @admin.action(description="Clean & re-import (delete existing data first)")
    def clean_and_reimport(self, request, queryset):
        for ci in queryset:
            try:
                run_content_import(ci, clean=True)
                self.message_user(
                    request,
                    f"'{ci}' re-imported: {ci.items_created} items, "
                    f"{ci.pages_created} pages, {ci.exercises_created} exercises.",
                    messages.SUCCESS,
                )
            except Exception as exc:
                self.message_user(request, f"'{ci}' failed: {exc}", messages.ERROR)
