# Generated by Django 6.0.5 on 2026-06-18 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_content", "0003_aicontent_prompt_messages"),
        ("content", "0003_section_created_by_sectionitem_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "learning goal",
                "verbose_name_plural": "learning goals",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LexicalItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vocab", "Vocabulary"),
                            ("verb", "Verb"),
                            ("phrase", "Phrase"),
                            ("grammar_rule", "Grammar Rule"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("pronoun", "Pronoun"),
                            ("article", "Article"),
                            ("particle", "Particle"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("audio_url", models.URLField(blank=True, default="")),
                ("frequency_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexical_items",
                        to="content.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "lexical item",
                "verbose_name_plural": "lexical items",
                "ordering": ["level", "frequency_rank"],
            },
        ),
        migrations.CreateModel(
            name="ItemRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("synonym", "Synonym"),
                            ("antonym", "Antonym"),
                            ("confusable", "Confusable"),
                            ("compound_of", "Compound Of"),
                            ("derivation", "Derivation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="knowledge.lexicalitem",
                    ),
                ),
                (
                    "to_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="knowledge.lexicalitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "item relationship",
                "verbose_name_plural": "item relationships",
            },
        ),
        migrations.CreateModel(
            name="GrammarRuleDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                ("pattern", models.CharField(blank=True, default="", max_length=255)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_rule_detail",
                        to="knowledge.lexicalitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "grammar rule detail",
                "verbose_name_plural": "grammar rule details",
            },
        ),
        migrations.CreateModel(
            name="ExampleSentence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
                ("translation", models.TextField()),
                ("audio_url", models.URLField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="knowledge.lexicalitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "example sentence",
                "verbose_name_plural": "example sentences",
                "ordering": ["item", "order"],
            },
        ),
        migrations.CreateModel(
            name="ModelClass",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "models_in_class",
                    models.ManyToManyField(
                        blank=True, related_name="model_classes", to="ai_content.llmmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "model class",
                "verbose_name_plural": "model classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NounDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("m", "Masculine (der)"),
                            ("f", "Feminine (die)"),
                            ("n", "Neuter (das)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("plural", models.CharField(blank=True, default="", max_length=255)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noun_detail",
                        to="knowledge.lexicalitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "noun detail",
                "verbose_name_plural": "noun details",
            },
        ),
        migrations.CreateModel(
            name="PhraseDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "formality_level",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("neutral", "Neutral"),
                            ("informal", "Informal"),
                            ("colloquial", "Colloquial"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("context", models.CharField(blank=True, default="", max_length=255)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phrase_detail",
                        to="knowledge.lexicalitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "phrase detail",
                "verbose_name_plural": "phrase details",
            },
        ),
        migrations.CreateModel(
            name="ReferenceSheet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[("table", "Table"), ("grid", "Grid"), ("notes", "Notes")],
                        max_length=20,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=list)),
                ("rows", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_sheets",
                        to="content.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "reference sheet",
                "verbose_name_plural": "reference sheets",
                "ordering": ["level", "order"],
            },
        ),
        migrations.CreateModel(
            name="VerbDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("separable_prefix", models.CharField(blank=True, default="", max_length=50)),
                (
                    "auxiliary_verb",
                    models.CharField(
                        blank=True,
                        choices=[("haben", "haben"), ("sein", "sein")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("conjugation_group", models.CharField(blank=True, default="", max_length=50)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verb_detail",
                        to="knowledge.lexicalitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "verb detail",
                "verbose_name_plural": "verb details",
            },
        ),
        migrations.AddIndex(
            model_name="lexicalitem",
            index=models.Index(fields=["type", "level"], name="knowledge_l_type_a9a145_idx"),
        ),
        migrations.AddIndex(
            model_name="lexicalitem",
            index=models.Index(
                fields=["level", "frequency_rank"], name="knowledge_l_level_i_b00f60_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lexicalitem",
            constraint=models.UniqueConstraint(
                fields=("text", "type", "level"), name="unique_item_per_type_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemrelationship",
            constraint=models.UniqueConstraint(
                fields=("from_item", "to_item", "relationship_type"),
                name="unique_item_relationship",
            ),
        ),
        migrations.AddIndex(
            model_name="examplesentence",
            index=models.Index(fields=["item", "order"], name="knowledge_e_item_id_6cd4b7_idx"),
        ),
    ]
