# Generated by Django 6.0.5 on 2026-06-17 11:52

from django.db import migrations


INITIAL_PACKS = [
    {
        "title": "German A1.1 — English",
        "slug": "a1-1-en",
        "level_code": "A1.1",
        "base_language": "en",
        "description": "Complete beginner German with English explanations. Covers basic grammar, essential vocabulary, common verbs, and everyday phrases for the Goethe A1 exam.",
        "grammar_count": 12,
        "vocab_count": 8,
        "exercise_count": 45,
    },
    {
        "title": "German A1.1 — فارسی",
        "slug": "a1-1-fa",
        "level_code": "A1.1",
        "base_language": "fa",
        "description": "آلمانی مقدماتی با توضیحات فارسی. شامل گرامر پایه، واژگان ضروری، افعال رایج و عبارات روزمره برای آزمون گوته A1.",
        "grammar_count": 12,
        "vocab_count": 8,
        "exercise_count": 45,
    },
    {
        "title": "German A1.2 — English",
        "slug": "a1-2-en",
        "level_code": "A1.2",
        "base_language": "en",
        "description": "Continue your A1 journey. Separable verbs, modal verbs, accusative case, time expressions, and more vocabulary for daily life.",
        "grammar_count": 10,
        "vocab_count": 6,
        "exercise_count": 38,
    },
    {
        "title": "German A2.1 — English",
        "slug": "a2-1-en",
        "level_code": "A2.1",
        "base_language": "en",
        "description": "Elementary German with dative case, two-way prepositions, comparative forms, and expanded vocabulary for travel, work, and health topics.",
        "grammar_count": 14,
        "vocab_count": 10,
        "exercise_count": 52,
    },
]


def seed_packs(apps, schema_editor):
    Pack = apps.get_model("packs", "Pack")
    Level = apps.get_model("content", "Level")

    for pack_data in INITIAL_PACKS:
        level_code = pack_data.pop("level_code")
        try:
            level = Level.objects.get(code=level_code)
        except Level.DoesNotExist:
            continue
        Pack.objects.get_or_create(
            slug=pack_data["slug"],
            defaults={**pack_data, "level": level},
        )


def remove_packs(apps, schema_editor):
    Pack = apps.get_model("packs", "Pack")
    slugs = [p["slug"] for p in INITIAL_PACKS]
    Pack.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_packs, remove_packs),
    ]
