# Generated by Django 6.0.5 on 2026-06-18 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
        ("packs", "0002_seed_initial_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="goals",
            field=models.ManyToManyField(
                blank=True, related_name="packs", to="knowledge.learninggoal"
            ),
        ),
        migrations.CreateModel(
            name="PackItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_items",
                        to="knowledge.lexicalitem",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_items",
                        to="packs.pack",
                    ),
                ),
            ],
            options={
                "verbose_name": "pack item",
                "verbose_name_plural": "pack items",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="pack",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="packs",
                through="packs.PackItem",
                to="knowledge.lexicalitem",
            ),
        ),
        migrations.CreateModel(
            name="PackReferenceSheet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_reference_sheets",
                        to="packs.pack",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_reference_sheets",
                        to="knowledge.referencesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "pack reference sheet",
                "verbose_name_plural": "pack reference sheets",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="pack",
            name="reference_sheets",
            field=models.ManyToManyField(
                blank=True,
                related_name="packs",
                through="packs.PackReferenceSheet",
                to="knowledge.referencesheet",
            ),
        ),
        migrations.AddConstraint(
            model_name="packitem",
            constraint=models.UniqueConstraint(fields=("pack", "item"), name="unique_pack_item"),
        ),
        migrations.AddConstraint(
            model_name="packreferencesheet",
            constraint=models.UniqueConstraint(
                fields=("pack", "sheet"), name="unique_pack_reference_sheet"
            ),
        ),
    ]
