# Generated by Django 6.0.5 on 2026-06-20 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_page_pagelexicalitem_page_items_pagepart_and_more'),
        ('knowledge', '0002_seed_goals'),
        ('packs', '0003_pack_goals_packitem_pack_items_packreferencesheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(choices=[('flashcard', 'Flashcard'), ('mcq_recognition', 'MCQ Recognition'), ('fill_blank', 'Fill in the Blank'), ('sentence_order', 'Sentence Order'), ('error_correction', 'Error Correction'), ('matching', 'Matching')], max_length=20)),
                ('source', models.CharField(choices=[('creator', 'Pack Creator'), ('engine', 'Auto-generated'), ('ai', 'AI-generated')], max_length=20)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='knowledge.lexicalitem')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='packs.pack')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='content.page')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorCorrectionExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=500)),
                ('error_start', models.PositiveIntegerField()),
                ('error_end', models.PositiveIntegerField()),
                ('correct_replacement', models.CharField(max_length=100)),
                ('corrected_sentence', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True, default='')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='error_correction', to='exercise_engine.exercise')),
            ],
            options={
                'verbose_name': 'error correction exercise',
                'verbose_name_plural': 'error correction exercises',
            },
        ),
        migrations.CreateModel(
            name='FillBlankExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_before', models.CharField(max_length=500)),
                ('text_after', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=100)),
                ('accept_alternatives', models.JSONField(blank=True, default=list)),
                ('hint', models.CharField(blank=True, default='', max_length=255)),
                ('explanation', models.TextField(blank=True, default='')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank', to='exercise_engine.exercise')),
            ],
            options={
                'verbose_name': 'fill blank exercise',
                'verbose_name_plural': 'fill blank exercises',
            },
        ),
        migrations.CreateModel(
            name='FlashcardExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_text', models.CharField(max_length=255)),
                ('back_text', models.CharField(max_length=255)),
                ('front_context', models.CharField(blank=True, default='', max_length=255)),
                ('back_context', models.CharField(blank=True, default='', max_length=255)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='exercise_engine.exercise')),
            ],
            options={
                'verbose_name': 'flashcard exercise',
                'verbose_name_plural': 'flashcard exercises',
            },
        ),
        migrations.CreateModel(
            name='MatchingExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.CharField(blank=True, default='', max_length=255)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='exercise_engine.exercise')),
            ],
            options={
                'verbose_name': 'matching exercise',
                'verbose_name_plural': 'matching exercises',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left', models.CharField(max_length=255)),
                ('right', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='exercise_engine.matchingexercise')),
            ],
            options={
                'verbose_name': 'matching pair',
                'verbose_name_plural': 'matching pairs',
                'ordering': ['matching', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MCQExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True, default='')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq', to='exercise_engine.exercise')),
            ],
            options={
                'verbose_name': 'MCQ exercise',
                'verbose_name_plural': 'MCQ exercises',
            },
        ),
        migrations.CreateModel(
            name='MCQChoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exercise_engine.mcqexercise')),
            ],
            options={
                'verbose_name': 'MCQ choice',
                'verbose_name_plural': 'MCQ choices',
                'ordering': ['mcq', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SentenceOrderExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumbled_words', models.JSONField()),
                ('correct_answers', models.JSONField()),
                ('hint', models.CharField(blank=True, default='', max_length=255)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_order', to='exercise_engine.exercise')),
            ],
            options={
                'verbose_name': 'sentence order exercise',
                'verbose_name_plural': 'sentence order exercises',
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['item', 'exercise_type'], name='exercise_en_item_id_46e8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['pack', 'exercise_type'], name='exercise_en_pack_id_52efa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingpair',
            constraint=models.UniqueConstraint(fields=('matching', 'order'), name='unique_matching_pair_order'),
        ),
        migrations.AddConstraint(
            model_name='mcqchoice',
            constraint=models.UniqueConstraint(fields=('mcq', 'order'), name='unique_mcq_choice_order'),
        ),
    ]
