# Generated by Django 6.0.5 on 2026-06-18 23:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("recognition", "Recognition"),
                            ("production", "Production"),
                            ("listening", "Listening"),
                            ("spelling", "Spelling"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("difficulty", models.FloatField(default=0.0)),
                ("stability", models.FloatField(default=0.0)),
                ("reps", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("state", models.PositiveSmallIntegerField(default=0)),
                ("last_review", models.DateTimeField(blank=True, null=True)),
                ("next_due", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_states",
                        to="knowledge.lexicalitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "memory state",
                "verbose_name_plural": "memory states",
                "ordering": ["next_due"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("response_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("scheduled_days", models.FloatField(default=0)),
                ("actual_days", models.FloatField(default=0)),
                ("difficulty_before", models.FloatField(default=0)),
                ("stability_before", models.FloatField(default=0)),
                ("difficulty_after", models.FloatField(default=0)),
                ("stability_after", models.FloatField(default=0)),
                (
                    "memory_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="memory_engine.memorystate",
                    ),
                ),
            ],
            options={
                "verbose_name": "review log",
                "verbose_name_plural": "review logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="memorystate",
            index=models.Index(fields=["user", "next_due"], name="memory_engi_user_id_4e3fcf_idx"),
        ),
        migrations.AddIndex(
            model_name="memorystate",
            index=models.Index(fields=["user", "state"], name="memory_engi_user_id_197dd1_idx"),
        ),
        migrations.AddConstraint(
            model_name="memorystate",
            constraint=models.UniqueConstraint(
                fields=("user", "item", "skill_type"), name="unique_memory_state"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["memory_state", "created_at"], name="memory_engi_memory__88f68b_idx"
            ),
        ),
    ]
