# Generated by Django 6.0.5 on 2026-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorystate',
            name='skill_type',
            field=models.CharField(choices=[('recognition', 'Recognition'), ('production', 'Production'), ('listening', 'Listening'), ('spelling', 'Spelling'), ('application', 'Application')], db_index=True, max_length=20),
        ),
    ]
