"use client";

import { useState } from "react";
import { Bookmark, Cpu, RefreshCw, Trash2 } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import type {
  AIContentResponse,
  AIExamplesResponse,
  AIExplanationResponse,
  AIQuizResponse,
} from "@/types/ai-content";

import { AIExamplesView } from "./ai-examples-view";
import { AIExplanationView } from "./ai-explanation-view";
import { AIQuizView } from "./ai-quiz-view";
import type { AIContentCardProps } from "./types";

export function AIContentCard({
  content,
  onSave,
  onDelete,
  onRegenerate,
  isDeleting,
}: AIContentCardProps) {
  const [saved, setSaved] = useState(content.is_saved);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [showRegenerateConfirm, setShowRegenerateConfirm] = useState(false);

  const handleSave = async () => {
    await onSave(content.id);
    setSaved(true);
  };

  return (
    <>
      <div className="rounded-lg border bg-card p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Cpu className="h-3.5 w-3.5" />
            <span>Generated by</span>
            <Badge variant="outline" className="text-xs">
              {content.model_used}
            </Badge>
          </div>
          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon-sm"
              onClick={() => setShowRegenerateConfirm(true)}
              title="Regenerate with this model"
            >
              <RefreshCw className="h-3.5 w-3.5" />
            </Button>
            <Button
              variant="ghost"
              size="icon-sm"
              onClick={() => setShowDeleteConfirm(true)}
              disabled={isDeleting}
              title="Delete this generation"
              className="text-destructive hover:text-destructive"
            >
              <Trash2 className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        {content.action_type === "examples" && content.response_json && (
          <AIExamplesView data={content.response_json as AIExamplesResponse} />
        )}
        {content.action_type === "quiz" && content.response_json && (
          <AIQuizView data={content.response_json as AIQuizResponse} />
        )}
        {content.action_type === "explanation" && content.response_json && (
          <AIExplanationView data={content.response_json as AIExplanationResponse} />
        )}

        {!content.response_json && (
          <div className="whitespace-pre-wrap rounded-md border bg-muted/50 p-3 text-sm">
            {content.response_text}
          </div>
        )}

        <Button
          variant={saved ? "secondary" : "outline"}
          size="sm"
          onClick={handleSave}
          disabled={saved}
          className="w-full"
        >
          <Bookmark className="mr-1.5 h-4 w-4" />
          {saved ? "Saved" : "Save to my collection"}
        </Button>
      </div>

      <ConfirmDialog
        open={showDeleteConfirm}
        onOpenChange={setShowDeleteConfirm}
        title="Delete this content?"
        description="This will permanently remove this AI-generated content. This action cannot be undone."
        confirmLabel="Delete"
        variant="destructive"
        isLoading={isDeleting}
        onConfirm={() => {
          setShowDeleteConfirm(false);
          onDelete(content.id);
        }}
      />

      <ConfirmDialog
        open={showRegenerateConfirm}
        onOpenChange={setShowRegenerateConfirm}
        title="Regenerate this content?"
        description="This will replace the current content with a new generation from the same model. The old content will be lost."
        confirmLabel="Regenerate"
        variant="destructive"
        isLoading={isDeleting}
        onConfirm={() => {
          setShowRegenerateConfirm(false);
          onRegenerate(content);
        }}
      />
    </>
  );
}
