# Generated by Django 6.0.5 on 2026-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content', '0002_llmmodel_remove_aicontent_unique_fingerprint_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontent',
            name='prompt_messages',
            field=models.JSONField(default=list),
        ),
    ]
